apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: gickup-blueprint
actions:
  backup:
    phases:
    - func: KubeExec
      name: takeBackup
      args:
        namespace: "{{ .Deployment.Namespace }}"
        pod: "{{ index .Deployment.Pods 0 }}"
        container: "gickup"
        command:  
          - bash
          - -o
          - errexit
          - -o
          - xtrace
          - -o
          - pipefail
          - -c
          - |
            gickup /config/conf.yml 
    - func: BackupData
      name: BackupToObjectStore
      args:
        namespace: "{{ .Deployment.Namespace }}"
        pod: "{{ index .Deployment.Pods 0 }}"
        container: kanister-tools
        encryptionKey: "testpassword"
        includePath: /backups
        backupArtifactPrefix: "{{ .Profile.Location.Bucket }}/gickup-backups"
    
      